### ISSUE TITLE
Solution to deprecated ui.window.locale

### ISSUE THREAD

**Issue by ensarhoxhaa** [bizz84/localization_riverpod_flutter#6]
I found this guide really helpful and appreciate your efforts in writing this. 

Since `ui.window.locale` is deprecated, what would be the alternative to use instead.

I made it work with `WidgetsBinding.instance.platformDispatcher.locale`, but I am not sure if it's the best and same solution as before.

**Comment by atnpem** [comment]
> I found this guide really helpful and appreciate your efforts in writing this.
> 
> Since `ui.window.locale` is deprecated, what would be the alternative to use instead.
> 
> I made it work with `WidgetsBinding.instance.platformDispatcher.locale`, but I am not sure if it's the best and same solution as before.

It's the solution provided by the official documentation : https://docs.flutter.dev/release/breaking-changes/window-singleton

> If no BuildContext is available, the PlatformDispatcher exposed by the bindings can be consulted directly.
> Code before migration:

```
double getTextScaleFactor() {
  return WidgetsBinding.instance.window.textScaleFactor;
}
```

> Code after migration:

```
double getTextScaleFactor() {
  // View.of(context).platformDispatcher.textScaleFactor if a BuildContext is available, otherwise:
  return WidgetsBinding.instance.platformDispatcher.textScaleFactor;
}
```

**Comment by julienlebren** [comment]
Issue fixed by this pr: https://github.com/bizz84/localization_riverpod_flutter/pull/7
